#yaml语法需要用空格格式化 类似python

name: ci

on: repository_dispatch
        
jobs:
# ================== 第一个 job，这只有一个 job ==================
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: setupSoft
        run: |
#          sudo apt-get update
#          sudo apt-get install ffmpeg
#          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone/
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONF }}
          EOF
          
      - name: download
        run: |
          echo '${{ github.event.client_payload.downurl }}'
#          curl '${{ github.event.client_payload.downurl }}' -o test.mp4
#          ffmpeg -i test.mp4 -vn -y -acodec copy '${{ github.event.client_payload.filename }}'.aac

          
      - name: Rclone Synchronizing file
        run: |
          echo '${{ github.event.client_payload.filename }}'
#          rclone copy '${{ github.event.client_payload.filename }}'.aac github:logo
