name: audio
on:
  repository_dispatch:
    types: getaudio
    
jobs:
# ================== 第一个 job，这只有一个 job ==================./bin/astisub -i test.ttml -o ${{ github.event.client_payload.filename }}.vtt
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x ./bin/astisub
#      - name: Clone repository
#        uses: actions/checkout@v1

      - name: setupSoft
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
          curl https://rclone.org/install.sh | sudo bash
          
      - name: download
        run: |
          curl '${{ github.event.client_payload.downurl }}' -o test.mp4
          curl '${{ github.event.client_payload.titleurl }}' -o test.ttml
          mkdir -p ~/.config/rclone/
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONF }}
          EOF
#          ffmpeg -i test.mp4 -vn -y -acodec copy ${{ github.event.client_payload.filename }}.aac
#          ./bin/astisub convert -i test.ttml -o ${{ github.event.client_payload.filename }}.vtt

      - name: toAcc
        run: ffmpeg -i test.mp4 -vn -y -acodec copy ${{ github.event.client_payload.filename }}.aac

      - name: accOk
        if: ${{ success() }}
        run: rclone copy ${{ github.event.client_payload.filename }}.aac github:logo
          
      - name: toVtt
        run: ./bin/astisub convert -i test.ttml -o ${{ github.event.client_payload.filename }}.vtt

      - name: vttOk
        if: ${{ success() }}
        run: rclone copy ${{ github.event.client_payload.filename }}.vtt github:logo
        
      - name: finnal
        run: echo "hello,ok"
        
#      - name: Rclone Synchronizing file
#        run: |
#          rclone lsf github:
#          echo '${{ github.event.client_payload.filename }}'
#          rclone copy ${{ github.event.client_payload.filename }}.aac github:logo
#          rclone copy ${{ github.event.client_payload.filename }}.vtt github:logo
