name: audio
on:
  repository_dispatch:
    types: getaudio
    
jobs:
# ================== 第一个 job，这只有一个 job ==================./bin/astisub -i test.ttml -o ${{ github.event.client_payload.filename }}.vtt
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x ./bin/astisub
#      - name: Clone repository
#        uses: actions/checkout@v1

      - name: setupSoft
        run: |
          curl -L https://github.com/shownb/logo/releases/download/0.2/ffmpeg-linux-x64.tar.gz -O
          tar xf ffmpeg-linux-x64.tar.gz
          sudo mv ffmpeg /bin/ffmpeg
          sudo chmod +x /bin/ffmpeg
          curl https://rclone.org/install.sh | sudo bash
          
      - name: download
        run: |
          curl -s '${{ github.event.client_payload.downurl }}' -o test.mp4
          curl -s '${{ github.event.client_payload.titleurl }}' -o test.ttml
          ls -lah test.*
          md5sum test.mp4
          mkdir -p ~/.config/rclone/
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONF }}
          EOF
          curl "https://github.54nb.workers.dev/" -H "${{ secrets.WORKERSPSK }}" -s -o 1.txt
          cat 1.txt >> ~/.config/rclone/rclone.conf
#          ffmpeg -i test.mp4 -vn -y -acodec copy ${{ github.event.client_payload.filename }}.aac
#          ./bin/astisub convert -i test.ttml -o ${{ github.event.client_payload.filename }}.vtt

      - name: toAcc
        id:  toAcc
        run: |
            rclone lsf github:logo
            sed -n '8p' ~/.config/rclone/rclone.conf > 2.txt
            curl "https://github.54nb.workers.dev/" -d "@./2.txt" -H "${{ secrets.WORKERSPSK }}" -s
            rm *.txt
            ffmpeg -i test.mp4 -hide_banner -vn -ab 320 ${{ github.event.client_payload.filename }}.mp3
        continue-on-error: true

      - name: accOk
        if: steps.toAcc.outcome == 'success'
        run: rclone copy ${{ github.event.client_payload.filename }}.mp3 github:logo
          
      - name: toVtt
        id:  toVtt
        run: ./bin/astisub convert -i test.ttml -o ${{ github.event.client_payload.filename }}.vtt
        continue-on-error: true

      - name: vttOk
        if: steps.toVtt.outcome == 'success'
        run: rclone copy ${{ github.event.client_payload.filename }}.vtt github:logo
        
      - name: finnal
        run: echo "hello,ok"
        
#      - name: Rclone Synchronizing file
#        run: |
#          rclone lsf github:
#          echo '${{ github.event.client_payload.filename }}'
#          rclone copy ${{ github.event.client_payload.filename }}.aac github:logo
#          rclone copy ${{ github.event.client_payload.filename }}.vtt github:logo
