name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: download
        run: |
          sudo apt-get update
          curl https://rclone.org/install.sh | sudo bash
      - name: curl
        run: |
          mkdir -p ~/.config/rclone/
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONF }}
          EOF
      - name: Rclone Synchronizing file
        run: |
          rclone copy install github:logo
