#yaml语法需要用空格格式化 类似python
#
name: ci

on: repository_dispatch
    inputs:
      downurl:
        description: 'mp4 url'
        required: true
        default: 'https://downloadzdf-a.akamaihd.net/mp4/zdf/21/02/210212_fr_neu_lot/2/210212_fr_neu_lot_3328k_p15v15.mp4'
      filename:
        description: 'file name'
        required: true
        default: 'test'
        
jobs:
# ================== 第一个 job，这只有一个 job ==================
  first_job:
    runs-on: ubuntu-latest
    steps:
#      - name: Clone repository
#        uses: actions/checkout@v2

      - name: setupSoft
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone/
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONF }}
          EOF
          
      - name: download
        run: |
          curl ${{ github.event.client_payload.downurl }} -o test.mp4
          ffmpeg -i test.mp4 -vn -y -acodec copy ${{ github.event.client_payload.filename }}.aac
          
      - name: Rclone Synchronizing file
        run: |
          rclone copy ${{ github.event.client_payload.filename }}.aac github:logo
